# Generated by Django 4.2 on 2023-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicalgenre',
            options={},
        ),
    ]
