# Generated by Django 4.2 on 2023-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_alter_musicalgenre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='music_app.song'),
        ),
        migrations.AddField(
            model_name='author',
            name='songs',
            field=models.ManyToManyField(related_name='authors', to='music_app.song'),
        ),
    ]
