# Generated by Django 4.2.1 on 2023-05-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0003_album_songs_author_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
