# Generated by Django 4.1.5 on 2023-05-18 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0004_alter_song_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="musicalGenre",
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_app.album",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="song",
            name="musicalGenre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="music_app.musicalgenre",
            ),
        ),
    ]
