# Generated by Django 4.1.5 on 2023-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0005_remove_author_musicalgenre_alter_song_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.TextField(max_length=100),
        ),
    ]
