# Generated by Django 4.1.5 on 2023-05-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_remove_author_songs_remove_song_audio_link'),
        ('music_app', '0007_song_slug'),
    ]

    operations = [
    ]
