# Generated by Django 4.1.5 on 2023-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='author',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
        migrations.AlterField(
            model_name='musicalgenre',
            name='genre',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, default='-', max_length=10, null=True),
        ),
    ]
