# Generated by Django 4.1.5 on 2023-05-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_remove_album_songs_remove_author_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums', to='music_app.author'),
        ),
        migrations.AlterField(
            model_name='musicalgenre',
            name='genre',
            field=models.TextField(default='Other'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_app.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_app.author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='musicalGenre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music_app.musicalgenre'),
        ),
    ]
