# Generated by Django 4.1.5 on 2023-05-21 16:17

from django.db import migrations, models
import music_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_remove_album_songs_remove_song_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=music_app.models.song_file_path),
        ),
    ]
