# Generated by Django 4.1.5 on 2023-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_remove_song_audio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_audioFile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
