# Generated by Django 4.1.5 on 2023-05-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0011_song_is_audiofile_alter_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_audioFile',
        ),
    ]
